#case "${EBUILD_PHASE}" in
#        preinst) 
#                DESC="${CATEGORY}/${PF}"
#                NUMBER=`snapper create -t pre -p -d "${DESC}"`
#                ;;
#        postinst) 
#                snapper create -t post --pre-number $NUMBER -d "${DESC}"
#                ;;
#esac
